language: node_js
node_js:
  - "8"
  - "10"
brancher:
  only:
    - "dev"
    - "master"
install:
  - "npm install"
  - "npm install coveralls --save-dev"
script:
  - "npm run test"
after_success: "npm run coverage"